### ISSUE TITLE
PANIE PROFESORZE MOZNA PROSIC 5?

### ISSUE THREAD

**Issue by Bucik797** [Bucik797/projekt-czolgi#112]

**Comment by JOtworowski** [comment]
Czy planujecie Panowie dodanie opcji odpalenia projektu z pliku .exe lub dodanie pakietu instalatora, który pozwoli na zainstalowanie gry? Jeśli chodzi o ocenę to jutro na zajęciach jeszcze porozmawiamy

**Comment by JOtworowski** [comment]
Tomorrow we'll talk about the project evaluation

**Comment by Bucik797** [comment]
> Czy planujecie Panowie dodanie opcji odpalenia projektu z pliku .exe lub dodanie pakietu instalatora, który pozwoli na zainstalowanie gry? Jeśli chodzi o ocenę to jutro na zajęciach jeszcze porozmawiamy

W README na samym dole jest pakiet instalacyjny i wszelkie informacje na temat gry ;)

**Comment by Bucik797** [comment]
> Czy planujecie Panowie dodanie opcji odpalenia projektu z pliku .exe lub dodanie pakietu instalatora, który pozwoli na zainstalowanie gry? Jeśli chodzi o ocenę to jutro na zajęciach jeszcze porozmawiamy

Miłego wieczoru i do zobaczenia jutro :D
