### ISSUE TITLE
Pakiet instalatora skonfigurowany pomyślnie, uprzejmie proszę o sprawdzenie

### ISSUE THREAD

**Issue by Bucik797** [Bucik797/projekt-czolgi#120]

**Comment by Bucik797** [comment]
Proszę o informację zwrotną, czy działa

**Comment by JOtworowski** [comment]
Projekt niezwykle trudny do oceny, ponieważ uważam że jest bardzo nierówny. Niektóre elementy są wykonane bardzo dobrze inne natomiast mają wyraźne mankamenty. Jako plusy mogę wskazać świetne udźwiękowienie, dopracowane menu i pozostałe ekrany interfejsu oraz przemyślaną progresję gracza. Jako minusy rzuca się w oczy oprawa graficzna. Brakuje jakichkolwiek animacji, poza tym na ostatniej planszy tekstury samochodów mają widoczne szare prostokąty, co można było stosunkowo łato usunąć lub znaleźć teksturę z przezroczystym tłem. Do tego część samochodów jeździ tyłem co także uważam za przejaw pośpiechu i braku zwracania uwagi na drobne rzeczy, które znacznie mogły by poprawić odbiór gry . Poza tym przeciwnicy przenikają przez ściany niezależnie od typu co też uważam za minus projektu. Podczas sprawdzania kodu zauważyłem także że wszyscy przeciwnicy poruszają się według tego samego bardzo prostego schematu działania co podejrzewałem już podczas grania.

Jeśli chodzi o wskazane przeze mnie wymagania to plik .exe dział i doceniam, że postarali się Panowie to poprawić. Prowadzenie projektu na gicie jest zrealizowane bardzo dobrze. Sprawdzając kod widziałem że zarówno dziedziczenie jak i unique_ptr zostały  wykorzystane.

Podsumowując niestety nie mogę ocenić projektu na więcej niż 87,5% mimo iż oprawa muzyczna bardzo mi się podobała to uważam że przeciwnicy występujący w grze wymagali by dopracowania w znacznym stopniu .

**Comment by Bucik797** [comment]
Dzień dobry. 

Uważam że ocena 87,5% za taki projekt jest conajmniej krzywdząca, poniżej spróbuję wyjaśnić dlaczego. 

Zostało nam zabrane 12.5% za brak jednej funkcji z animacją ruchu przeciwników i pathfindingu 

Wspominał Pan nie raz że mamy nie umierać za efekty graficzne, że lepiej ten czas poświęcić na szkielet kodu, więc tak zrobiłem, samochody jeżdżące tyłem to kwestia dosłownie jednej linijki kodu, to było zwykłe przeoczenie z mojej strony, za które przepraszam 

Kwestia pathfindingu 

Brak pathfindingu to było celowe działanie, podobnie jak nie wyświetlanie poziomu hp gracza i przeciwników. Miało to na celu wprowadzenie większych emocji i trudności podczas rozgrywki tak, żeby gracz nie mógł stać w miejscu i po prostu strzelać. Wymusza to na odbiorcy gry ciągłe skupienie podczas gry 

Cały interfejs gry, poruszanie się po menu i innych oknach, system progresji, brak bugów, 4 rodzaje przeciwników, z których każdy z nich ma inne cechy, których nie będę teraz wypunktowywał, 3 czołgi z których również każdy z nich ma swoje mocne i słabe strony, 4 mapy skonfigurowane wraz z rosnącym poziomem trudności, github prowadzony w sposób ponadprogramowy, obiektowość i przejrzystość kodu. 

To wszystko świadczy o tym że projekt nie był napisany w 2 nocki i zasługuje na więcej niż 87.5% 

Biorąc pod uwagę wszystkie wypunktowane przez Pana zalety naszego projektu, osobiście uważam że problem z poruszającymi się samochodami na ostatniej mapie i brakiem animacji poruszania się przeciwników został wyolbrzymiony zasłaniając jednocześnie wszystkie zalety gry 

Proszę o wyjaśnienie, dlaczego tak małe mankamenty graficzne wpłynęły aż tak znacząco na obniżenie oceny, zwłaszcza, że widział Pan ten projekt na gotowo nie mając do niego żadnych zastrzeżeń poza niedziałającą jeszcze wtedy instalką 

Z wyrazami szacunku, 

Dominik But gr LAB2 wtorek 16:50-18:20 

Współtwórca DS4 TANKS

**Comment by JOtworowski** [comment]
Dzień dobry

Rozumiem, że ma Pan wątpliwości odnośnie oceny. Postaram wytłumaczyć dokładnie o co mi chodziło. Jeśli chodzi o brak jakichkolwiek animacji to pamiętam, że o tym problemie wspominałem już na zajęciach. Jeśli chodzi o brak pathfindingu to jestem w stanie zrozumieć, że w pewnym stopniu jest to decyzja dotycząca balansu gry i nie wskazywałbym tego jako problem jeśli dotyczyło by to jednego lub dwóch przeciwników. Jednakże na przedostatnich zajęciach mówiłem chciałem żeby przeciwnicy działali według różnych modeli zachowania ( podałem że idealnie byłoby 3 różne). Podczas ostatnich zajęć nie zauważyłem tego, jednak podczas testowania projektu miałem wrażenie że wszyscy przeciwnicy poruszają się tak samo, dokładnie sprawdziłem to w kodzie i tam rzeczywiście meleEnemy i rangeEnemy (o ile dobrze pamiętam nazwy) poruszają się według dokładnie takiego samego bloku kodu. Tekstura samochodu też nie rzuciła mi się w oczy jak dużo działo się na ekranie. Jeśli chodzi o nieumieranie za efekty graficzne to nie miałbym problemu jeśli tekstury miałyby nieskomplikowane animacje, czy nie były spójne "artystycznie", natomiast szare tło w teksturze samochodu oceniam jako pewną niedoróbkę, ponieważ daje on efekt wklejenia "obcego elementu".

Gdzie głównymi elementami obniżającymi ocenę jest brak różnorodnych zachowań przeciwników, a także brak animacji, którego nie uważam za mały mankament, do tego kwestia tekstury o której pisałem już wcześniej. Powtórzę też to co pisałem wcześniej odnośnie pathfindingu, rozumiem że w pewnym stopniu była to kwestia dotycząca balansu, jednak uważam że minusem jest to że wszyscy przeciwnicy tak działają, a nie np. tylko latające demony i jakieś jeszcze jeden typ co powaliło by osiągnąć efekt założony przez panów a jednocześnie rozwiązało problem z jednakowym zachowaniem wszystkich przeciwników.

Podsumowując tak jak pisałem projekt uważam pod pewnymi względami za bardzo dobry (menu i interface, muzyka) pod innymi za dobry (progresja gry, stworzenie 4 map), niestety pod pewnymi jest co najwyżej solidny (zachowanie przeciwników, nieanimowane tekstury) i posiadający pewne niedoróbki. 

Rozumiem, że zależy Panu na ocenie 4,5, jednak o ile mogę podnieść ocenę o 2,5% (do 90%) za ogólnie bardzo pozytywne pierwsze wrażenie i świetnie wyglądające menu to uważam że nie mogę tego zrobić o całe 5 %, ponieważ ocenę powyżej 90% dotychczas uzyskiwały projekty dużo bardziej dopracowane pod kątem grafiki i zachowania przeciwników. Tematu naszych negocjacji jeszcze nie zamykam. Jeśli nadal czuje się Pan niesprawiedliwie oceniony do może Pan jeszcze odnieść się do mojej opinii.

Pozdrawiam
Jakub Otworowski

PS Nie uważam że projekt był robiony w 2 noce. Bardziej mam wrażenie, że problem wynikał z priorytety podczas prac zostały rozłożone w taki sposób, że pojawiły się opisane przeze mnie problemy

**Comment by Bucik797** [comment]
Dzień dobry Panie Jakubie,
Dziękuję za odpowiedź i szczegółowe wyjaśnienia. Doceniam poświęcony czas i konstruktywną krytykę. Pragnę jednak jeszcze raz odnieść się do niektórych punktów, aby spróbować przekonać Pana do podwyższenia oceny o dodatkowe 2,5%.
Różnorodność zachowań przeciwników
 Rzeczywiście, meleEnemy i rangeEnemy poruszają się według tego samego bloku kodu. Niemniej jednak, różnią się one sposobem ataku i poruszania się, co wpływa na strategię gry. Melee przeciwnicy (zombie i creepery) atakują bezpośrednio czy to poprzez wybuch czy to zadając obrażenia kontaktowe rozłożone odpowiednio w czasie, podczas gdy range przeciwnicy atakują z dystansu, co wymusza na graczu różne podejścia do walki z nimi. (Każdy przeciwnik ma inną ilość hp, inną prędkość poruszania się, inne obrażenia, inne miejsce pojawiania się na mapie w zależności od jej stopnia trudności, a rangeEnemy inną prędkość i wielkość pocisku).Myślę, że to także jest pewien poziom różnorodności, który mógł nie być w pełni zauważalny podczas testowania.
Animacje
Zgadzam się, że brak animacji poruszania się to niedopatrzenie, jednak warto podkreślić, że wszystkie inne aspekty graficzne były starannie dopracowane. Menu, interfejs, muzyka i ogólna spójność projektu były na wysokim poziomie, co również wymagało dużego nakładu pracy. Proszę o rozważenie, że animacje poruszania się, choć ważne, są tylko jednym z wielu elementów składających się na całość projektu.
Priorytety 
Faktycznie, nasze priorytety mogły wpłynąć na powstanie opisanych przez Pana problemów. Chciałbym jednak podkreślić, że pracując nad projektem, stawialiśmy na stabilność, brak błędów oraz przemyślaną mechanikę gry. Wiele z tych elementów zostało docenionych, ale uważam, że zasługują one na większe uznanie w końcowej ocenie.
Poziom dopracowania
Proszę również wziąć pod uwagę, że nasz projekt, mimo pewnych braków, wyróżniał się w wielu innych aspektach, takich jak spójność interfejsu, mechaniki gry oraz brak błędów, co również świadczy o wysokim poziomie dopracowania.
Biorąc pod uwagę powyższe argumenty, proszę o ponowne rozważenie możliwości podwyższenia oceny o dodatkowe 2,5%. Wierzę, że nasz projekt, mimo pewnych niedociągnięć, zasługuje na uznanie za innowacyjność i ogólną jakość wykonania.
Z wyrazami szacunku
Dominik But gr LAB2
wtorek 16:50-18:20 
Współtwórca DS4 TANKS
